### ISSUE TITLE
Yea man this guy jeff keeps dying in phas

### ISSUE THREAD

**Issue by nshinn14** [kimjeff49/song-recommendations#7]
# Bruh.jpg

**Comment by directcontact** [comment]
hey can you send me reprod steps

**Comment by nshinn14** [comment]
Yeah 1 sec

**Comment by nshinn14** [comment]
https://www.youtube.com/watch?v=FaPbyQMYG8Y

**Comment by directcontact** [comment]
Seems this is a problem with the riot api component, can you submit this on discord.js's github issue tracker?
