### ISSUE TITLE
website not working

### ISSUE THREAD

**Issue by nshinn14** [kimjeff49/song-recommendations#8]
See screenshot

![image](https://user-images.githubusercontent.com/16260875/97250359-2b33ef80-17dc-11eb-83b1-1cb9a541ed55.png)

**Comment by directcontact** [comment]
um

**Comment by directcontact** [comment]
subscribe to my patreon and ill show it to you

**Comment by directcontact** [comment]
https://www.twitch.tv/pokimane is my patreon

**Comment by nshinn14** [comment]
Hey man congrats
![image](https://user-images.githubusercontent.com/16260875/97250481-6c2c0400-17dc-11eb-9915-2d859e949c66.png)

**Comment by nshinn14** [comment]
link your na.op.gg you wont

**Comment by directcontact** [comment]
https://na.op.gg/summoner/userName=doublelift
